<?xml version="1.0" encoding="UTF-8"?><testrun name="testSodukoSolver.getCheckDigitInBox" project="SodukoSolver" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="test.testSodukoSolver" time="0.02" displayname="testSodukoSolver" uniqueid="[engine:junit-jupiter]/[class:test.testSodukoSolver]">
    <testcase name="getCheckDigitInBox" classname="test.testSodukoSolver" time="0.02" displayname="gets the digit in box row" uniqueid="[engine:junit-jupiter]/[class:test.testSodukoSolver]/[method:getCheckDigitInBox()]">
      <failure>java.lang.AssertionError: expected:&lt;1&gt; but was:&lt;0&gt;&#13;
	at junit@1000/org.junit.Assert.fail(Assert.java:89)&#13;
	at junit@1000/org.junit.Assert.failNotEquals(Assert.java:835)&#13;
	at junit@1000/org.junit.Assert.assertEquals(Assert.java:647)&#13;
	at junit@1000/org.junit.Assert.assertEquals(Assert.java:633)&#13;
	at SodukoSolver/test.testSodukoSolver.getCheckDigitInBox(testSodukoSolver.java:108)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
